version: "3"
services:
  frontend:
    build: ./frontend
    container_name: front_app
    image: localhost:5000/front_app
    networks:
      - front
    ports:
      - "3000:80"

  backend:
    build:
      context: lib_catalog
      dockerfile: ./Dockerfile_dj
    container_name: back
    image: localhost:5000/back
    networks:
      - front
      - back_db
    ports:
      - "8000:8000"
    depends_on:
      - "database"

  database:
    container_name: database
    image: postgres:bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      back_db:
        aliases:
          - database
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  back_db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          
  front:
    driver: bridge
    ipam:
      config:
        - subnet: "172.0.1.0/24"

