FROM python:bullseye
WORKDIR /django
RUN useradd -d /django -s /usr/sbin/nologin django && chown -R django /django
USER django
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
CMD ["./start.sh"]
